name: Python Packaging Workflow

on:
  pull_request:
    branches:
      - dummy-branches

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Tree
        run: sudo apt-get install tree -y

      - name: Display Tree Before Building
        run: tree

      - name: Build Package
        run: |
          pip install build
          python -m build

      - name: Display Tree After Building
        run: tree

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Python-Package-Artifacts-MLE
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: my-env
          environment-file: env.yml
          auto-activate-base: false

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: Python-Package-Artifacts-MLE

      - name: Install Package
        run: |
          pip install python_package-0.0.1-py3-none-any.whl

      - name: Run nonstandardcode.py
        run: python -m HousePricePrediction.nonstandardcode